steps:
- step: Segmentation
  settings:
    model: yolo
    model_settings:
      model: /Users/arthurborgerthorkildsen/Downloads/Others/model-test/line_region_model.pt
- step: TextRecognition
  settings:
    model: TrOCR
    model_settings:
      model: /Users/arthurborgerthorkildsen/Downloads/Others/pylaia-norhand-v3
- step: OrderLines
- step: Export
  settings:
    format: txt
    dest: outputs
